export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAIL = "FETCH_GROUPS_FAIL";
export const FETCH_AUTH_TOKEN_SUCCESS = "FETCH_AUTH_TOKEN_SUCCESS";
export const FETCH_USER_GROUPS_SUCCESS = "FETCH_USER_GROUPS_SUCCESS";
export const GET_CURRENT_GROUP = "GET_CURRENT_GROUP";


export const FETCH_DELAY_STORIES = "FETCH_DELAY_STORIES";
export const FETCH_DELAY_STORIES_SUCCESS = "FETCH_DELAY_STORIES_SUCCESS";

